//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html;charset=utf-8&quot; /&gt;
        ///    &lt;title&gt;Invoice&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            margin: 0;
        ///        }
        ///
        ///        div.PdfMain {
        ///            font-family: Verdana;
        ///            font-size: 10pt;
        ///            overflow: hidden;
        ///            white-space: nowrap;
        ///            wid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(function () {{
        ///    $(&apos;#{0}_leftValues option&apos;).sort(LBT.SortOptions).appendTo(&apos;#{0}_leftValues&apos;);
        ///    $(&apos;#{0} option&apos;).sort(LBT.SortOptions).appendTo(&apos;#{0}&apos;);
        ///    $(&apos;form&apos;).submit(function () {{
        ///        $(&apos;#{0} option&apos;).attr(&apos;selected&apos;, &apos;selected&apos;);
        ///    }});
        ///}});
        ///
        ///$(&apos;#{0}_btnLeft&apos;).click(function () {{
        ///    var selectedItem = $(&apos;#{0} option:selected&apos;);
        ///    $(&apos;#{0}_leftValues&apos;).append(selectedItem);
        ///    $(&apos;#{0}_leftValues option&apos;).sort(LBT.SortOptions).appendTo(&apos;#{0}_leftValues&apos;);
        ///}});
        ///
        ///$(&apos;#{0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MultiSelectListBoxTemplate {
            get {
                return ResourceManager.GetString("MultiSelectListBoxTemplate", resourceCulture);
            }
        }
    }
}
