//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Pěkný den,
        ///
        ///systém CLA Vám rezervoval místo na akci Název akce do 18. 03. 2015.
        ///Pokud do té doby neobdržíme platbu podle níže uvedených instrukcí, bude rezervace zrušena.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///  Název: Název akce
        ///  Od: 31.03.2015 10:10:00
        ///  Do: 31.03.2015 11:00:00
        ///  Obec: Praha 9
        ///  Ulice: Pod Harfou
        ///  Organizátor: Červený Leoš
        ///  Přednášející: asdf
        ///  
        ///  Potřebné s sebou:
        ///&lt;p&gt;Text,&amp;nbsp;&lt;strong&gt;tučn&amp;eacute;,&amp;nbsp;&lt;/strong&gt;&lt;em&gt;kurz&amp;iacute;va.&lt;/em&gt;&lt;/p&gt;
        ///&lt;p&gt;Dlouh&amp;yacute; blok textu.&amp;nbs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlEmail {
            get {
                return ResourceManager.GetString("HtmlEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vážení uživatelé CLA,
        ///
        ///technické problémy v komunikaci s Bankou se povedlo úspěšně vyřešit a aplikace CLA v nové verzi
        ///je již plně dostupná.
        ///
        ///Děkujeme za pochopení, hezký den,
        ///
        ///CLA Tým
        ///.
        /// </summary>
        internal static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mov_bbb {
            get {
                object obj = ResourceManager.GetObject("mov_bbb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Pěkný den,
        ///
        ///systém CLA Vám rezervoval místo na akci Název akce do 18. 03. 2015.
        ///Pokud do té doby neobdržíme platbu podle níže uvedených instrukcí, bude rezervace zrušena.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///  Název: Název akce
        ///  Od: 31.03.2015 10:10:00
        ///  Do: 31.03.2015 11:00:00
        ///  Obec: Praha 9
        ///  Ulice: Pod Harfou
        ///  Organizátor: Červený Leoš
        ///  Přednášející: asdf
        ///  
        ///  Potřebné s sebou:
        ///
        ///Text, tučné, kurzíva.
        ///Dlouhý blok textu. Dlouhý blok textu. Dlouhý blok textu. Dlouhý blok textu. Dlouhý blok [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlainEmail {
            get {
                return ResourceManager.GetString("PlainEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vážení uživatelé CLA
        ///
        ///Od pondělí 3.11.2014 přicházejí další zásadní změny v CLA aplikaci.
        ///
        ///    1. Placené akce v CLA obsahují i povinně specifický symbol, lidé na něj nejsou zvyklí a zapomínají na něj. Je nutné při platbách uvádět i specifický symbol.
        ///    2. Je nová doména www.czechlyons.com – je už aktivní a původní adresa lbt.aspone.cz je přesměrována na nový web. Nic ostatního se nemění. Už to neoznamuje chybu certifikátu. Pro jistotu doporučuji smazat historii v prohlížeči, který si může pamatovat  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SendEmailText {
            get {
                return ResourceManager.GetString("SendEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cerveny.leos@seznam.cz
        ///mikeska.zdenek@seznam.cz
        ///bedrich.nikl@gmail.com
        ///alda.kocourek@gmail.com
        ///jan.tomec56@gmail.com
        ///cervena.aljona@gmail.com
        ///niklbedrich@gmail.com
        ///jiri.vanecek7@gmail.com
        ///ales.kavulok@gmail.com
        ///ladislavmiska@gmail.com
        ///janakoucka1@gmail.com
        ///jan.kolodej@gmail.com
        ///jan@atep.cz
        ///rptrading99@gmail.com
        ///mstrmiskova@gmail.com
        ///ondrej.sikyr@gmail.com
        ///eva.vachova1@gmail.com
        ///mara.machacek@seznam.cz
        ///ves.vojtech@gmail.com
        ///sikyr.jakub9@gmail.com
        ///cernovsky.tomas@gmail.com
        ///knezkak@gmail.c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
