// <auto-generated />
namespace LBT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OptimizedModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OptimizedModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201401181840001_OptimizedModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
