// <auto-generated />
namespace LBT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpgradeV21122 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpgradeV21122));
        
        string IMigrationMetadata.Id
        {
            get { return "201509090728277_UpgradeV2-1-1-22"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
