// <auto-generated />
namespace LBT.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UpgradeV21223 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpgradeV21223));
        
        string IMigrationMetadata.Id
        {
            get { return "201509180715262_UpgradeV2-1-2-23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
