//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Resources.FieldResource", typeof(FieldResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdit nové heslo.
        /// </summary>
        public static string Account_ConfirmPassword_Name {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo.
        /// </summary>
        public static string Account_NewPassword_Name {
            get {
                return ResourceManager.GetString("Account_NewPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Současné heslo.
        /// </summary>
        public static string Account_OldPassword_Name {
            get {
                return ResourceManager.GetString("Account_OldPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo.
        /// </summary>
        public static string Account_Password_Name {
            get {
                return ResourceManager.GetString("Account_Password_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit se trvale?.
        /// </summary>
        public static string Account_RememberMe_Name {
            get {
                return ResourceManager.GetString("Account_RememberMe_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzuji, že mám povolení ke zpracování osobních údajů od historicky zadaných kontaktů.
        /// </summary>
        public static string AccountModelView_ConfirmContacts_Name {
            get {
                return ResourceManager.GetString("AccountModelView_ConfirmContacts_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhlas s odstraněním účtu a již zadaných kontaktů.
        /// </summary>
        public static string AccountModelView_ConfirmDeleteAccount_Name {
            get {
                return ResourceManager.GetString("AccountModelView_ConfirmDeleteAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÚ.
        /// </summary>
        public static string BankAccount_AccountId_Name {
            get {
                return ResourceManager.GetString("BankAccount_AccountId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ bankovního účtu.
        /// </summary>
        public static string BankAccount_BankAccountType_Name {
            get {
                return ResourceManager.GetString("BankAccount_BankAccountType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelé používající účet.
        /// </summary>
        public static string BankAccount_BankAccountUsers_Name {
            get {
                return ResourceManager.GetString("BankAccount_BankAccountUsers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string BankAccount_IBAN_Name {
            get {
                return ResourceManager.GetString("BankAccount_IBAN_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Majitel účtu.
        /// </summary>
        public static string BankAccount_Owner_Name {
            get {
                return ResourceManager.GetString("BankAccount_Owner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druhý BÚ.
        /// </summary>
        public static string BankAccount_SecondAccountId_Name {
            get {
                return ResourceManager.GetString("BankAccount_SecondAccountId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT.
        /// </summary>
        public static string BankAccount_SWIFT_Name {
            get {
                return ResourceManager.GetString("BankAccount_SWIFT_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token účtu.
        /// </summary>
        public static string BankAccount_Token_Name {
            get {
                return ResourceManager.GetString("BankAccount_Token_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platnost do.
        /// </summary>
        public static string BankAccount_ValidTo_Name {
            get {
                return ResourceManager.GetString("BankAccount_ValidTo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Částka.
        /// </summary>
        public static string BankAccountHistory_Ammount_Name {
            get {
                return ResourceManager.GetString("BankAccountHistory_Ammount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protiúčet.
        /// </summary>
        public static string BankAccountHistory_Exchange_Name {
            get {
                return ResourceManager.GetString("BankAccountHistory_Exchange_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KS.
        /// </summary>
        public static string BankAccountHistory_Ks_Name {
            get {
                return ResourceManager.GetString("BankAccountHistory_Ks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        public static string BankAccountHistory_Ss_Name {
            get {
                return ResourceManager.GetString("BankAccountHistory_Ss_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS.
        /// </summary>
        public static string BankAccountHistory_Vs_Name {
            get {
                return ResourceManager.GetString("BankAccountHistory_Vs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Info.
        /// </summary>
        public static string Contact_BusinessInfoParticipated_Name {
            get {
                return ResourceManager.GetString("Contact_BusinessInfoParticipated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neaktivní kontakt.
        /// </summary>
        public static string Contact_ContactDead_Name {
            get {
                return ResourceManager.GetString("Contact_ContactDead_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum oslovení.
        /// </summary>
        public static string Contact_FirstContacted_Name {
            get {
                return ResourceManager.GetString("Contact_FirstContacted_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalace a školení mob. apl..
        /// </summary>
        public static string Contact_MobileApplicationInstalledAndTrained_Name {
            get {
                return ResourceManager.GetString("Contact_MobileApplicationInstalledAndTrained_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potenciál.
        /// </summary>
        public static string Contact_Potential_Name {
            get {
                return ResourceManager.GetString("Contact_Potential_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 1. schůzky.
        /// </summary>
        public static string Contact_Presented_Name {
            get {
                return ResourceManager.GetString("Contact_Presented_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum registrace.
        /// </summary>
        public static string Contact_Registrated_Name {
            get {
                return ResourceManager.GetString("Contact_Registrated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setkání týmu.
        /// </summary>
        public static string Contact_TeamMeetingParticipated_Name {
            get {
                return ResourceManager.GetString("Contact_TeamMeetingParticipated_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Převodní kurz vůči CZK.
        /// </summary>
        public static string Currency_ExchangeRateToCZK_Name {
            get {
                return ResourceManager.GetString("Currency_ExchangeRateToCZK_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum přístupu do CLA.
        /// </summary>
        public static string Global_AccessGranted_Name {
            get {
                return ResourceManager.GetString("Global_AccessGranted_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Global_Address_Name {
            get {
                return ResourceManager.GetString("Global_Address_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bankovní účet.
        /// </summary>
        public static string Global_BankAccount_Name {
            get {
                return ResourceManager.GetString("Global_BankAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturační údaje.
        /// </summary>
        public static string Global_BillingInformation_Name {
            get {
                return ResourceManager.GetString("Global_BillingInformation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvóta počtu s jednotkami (nakupujících).
        /// </summary>
        public static string Global_BuyersQuota_Name {
            get {
                return ResourceManager.GetString("Global_BuyersQuota_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obec.
        /// </summary>
        public static string Global_City_Name {
            get {
                return ResourceManager.GetString("Global_City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhlas se zpracováním svých osobních údajů.
        /// </summary>
        public static string Global_ConfirmOwnPersonalData_Name {
            get {
                return ResourceManager.GetString("Global_ConfirmOwnPersonalData_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrzuji, že mám povolení ke zpracování osobních údajů od zadaného kontaktu/zadaných kontaktů.
        /// </summary>
        public static string Global_ConfirmPersonalData_Name {
            get {
                return ResourceManager.GetString("Global_ConfirmPersonalData_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souhlas s obchodními podmínkami.
        /// </summary>
        public static string Global_ConfirmTermsAndConditions_Name {
            get {
                return ResourceManager.GetString("Global_ConfirmTermsAndConditions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet kontaktovaných.
        /// </summary>
        public static string Global_ContactedPeopleCount_Name {
            get {
                return ResourceManager.GetString("Global_ContactedPeopleCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet kontaktovaných za měsíc.
        /// </summary>
        public static string Global_ContactedPeopleCountLastMonth_Name {
            get {
                return ResourceManager.GetString("Global_ContactedPeopleCountLastMonth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Měna.
        /// </summary>
        public static string Global_Currency_Name {
            get {
                return ResourceManager.GetString("Global_Currency_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Global_Date_Name {
            get {
                return ResourceManager.GetString("Global_Date_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIČ.
        /// </summary>
        public static string Global_DIC_Name {
            get {
                return ResourceManager.GetString("Global_DIC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okres.
        /// </summary>
        public static string Global_District_Name {
            get {
                return ResourceManager.GetString("Global_District_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Global_Email_Name {
            get {
                return ResourceManager.GetString("Global_Email_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 1.
        /// </summary>
        public static string Global_Email1_Name {
            get {
                return ResourceManager.GetString("Global_Email1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email 2.
        /// </summary>
        public static string Global_Email2_Name {
            get {
                return ResourceManager.GetString("Global_Email2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tělo emailu příjemce.
        /// </summary>
        public static string Global_EmailBody_Name {
            get {
                return ResourceManager.GetString("Global_EmailBody_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět emailu příjemce.
        /// </summary>
        public static string Global_EmailSubject_Name {
            get {
                return ResourceManager.GetString("Global_EmailSubject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string Global_FirstName_Name {
            get {
                return ResourceManager.GetString("Global_FirstName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IČO.
        /// </summary>
        public static string Global_ICO_Name {
            get {
                return ResourceManager.GetString("Global_ICO_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor pro import.
        /// </summary>
        public static string Global_ImportFile_Name {
            get {
                return ResourceManager.GetString("Global_ImportFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string Global_LastName_Name {
            get {
                return ResourceManager.GetString("Global_LastName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyoness ID.
        /// </summary>
        public static string Global_LyonessId_Name {
            get {
                return ResourceManager.GetString("Global_LyonessId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka.
        /// </summary>
        public static string Global_Note_Name {
            get {
                return ResourceManager.GetString("Global_Note_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pořadí.
        /// </summary>
        public static string Global_Order_Name {
            get {
                return ResourceManager.GetString("Global_Order_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilní telefon.
        /// </summary>
        public static string Global_PhoneNumber1_Name {
            get {
                return ResourceManager.GetString("Global_PhoneNumber1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        public static string Global_PhoneNumber1Short_Name {
            get {
                return ResourceManager.GetString("Global_PhoneNumber1Short_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Global_PhoneNumber2_Name {
            get {
                return ResourceManager.GetString("Global_PhoneNumber2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Premium členství.
        /// </summary>
        public static string Global_PremiumMembershipGranted_Name {
            get {
                return ResourceManager.GetString("Global_PremiumMembershipGranted_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvóta PP.
        /// </summary>
        public static string Global_PremiumPartnersQuota_Name {
            get {
                return ResourceManager.GetString("Global_PremiumPartnersQuota_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvóta PP za měsíc.
        /// </summary>
        public static string Global_PremiumPartnersQuotaLastMonth_Name {
            get {
                return ResourceManager.GetString("Global_PremiumPartnersQuotaLastMonth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSČ.
        /// </summary>
        public static string Global_PSC_Name {
            get {
                return ResourceManager.GetString("Global_PSC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvóta registrací.
        /// </summary>
        public static string Global_RegistredPeopleQuota_Name {
            get {
                return ResourceManager.GetString("Global_RegistredPeopleQuota_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvóta registrací za měsíc.
        /// </summary>
        public static string Global_RegistredPeopleQuotaLastMonth_Name {
            get {
                return ResourceManager.GetString("Global_RegistredPeopleQuotaLastMonth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Global_Role_Name {
            get {
                return ResourceManager.GetString("Global_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druhý bankovní účet.
        /// </summary>
        public static string Global_SecondBankAccount_Name {
            get {
                return ResourceManager.GetString("Global_SecondBankAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string Global_Skype_Name {
            get {
                return ResourceManager.GetString("Global_Skype_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkoly.
        /// </summary>
        public static string Global_Tasks_Name {
            get {
                return ResourceManager.GetString("Global_Tasks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        public static string Global_Title_Name {
            get {
                return ResourceManager.GetString("Global_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Global_Video_Name {
            get {
                return ResourceManager.GetString("Global_Video_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor návodu.
        /// </summary>
        public static string Manual_File_Name {
            get {
                return ResourceManager.GetString("Manual_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je návod dostupný i pro hosta?.
        /// </summary>
        public static string Manual_IsAccessForAuthGuest_Name {
            get {
                return ResourceManager.GetString("Manual_IsAccessForAuthGuest_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je návod stažitelný?.
        /// </summary>
        public static string Manual_IsDownloadable_Name {
            get {
                return ResourceManager.GetString("Manual_IsDownloadable_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ návodu.
        /// </summary>
        public static string ManualType_Title_Name {
            get {
                return ResourceManager.GetString("ManualType_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulice.
        /// </summary>
        public static string Meeting_AddressLine1_Name {
            get {
                return ResourceManager.GetString("Meeting_AddressLine1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potřebné s sebou.
        /// </summary>
        public static string Meeting_BringYourOwn_Name {
            get {
                return ResourceManager.GetString("Meeting_BringYourOwn_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celková kapacita.
        /// </summary>
        public static string Meeting_Capacity_Name {
            get {
                return ResourceManager.GetString("Meeting_Capacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum do.
        /// </summary>
        public static string Meeting_DateFinishTime_Name {
            get {
                return ResourceManager.GetString("Meeting_DateFinishTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum od.
        /// </summary>
        public static string Meeting_DateStartTime_Name {
            get {
                return ResourceManager.GetString("Meeting_DateStartTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den.
        /// </summary>
        public static string Meeting_Day_Name {
            get {
                return ResourceManager.GetString("Meeting_Day_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet přihlášených.
        /// </summary>
        public static string Meeting_FillCapacity_Name {
            get {
                return ResourceManager.GetString("Meeting_FillCapacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Meeting_FinishTime_Name {
            get {
                return ResourceManager.GetString("Meeting_FinishTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volná kapacita.
        /// </summary>
        public static string Meeting_FreeCapacity_Name {
            get {
                return ResourceManager.GetString("Meeting_FreeCapacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvánka.
        /// </summary>
        public static string Meeting_InvitationCardUrl_Name {
            get {
                return ResourceManager.GetString("Meeting_InvitationCardUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromá akce.
        /// </summary>
        public static string Meeting_IsMeetingPrivate_Name {
            get {
                return ResourceManager.GetString("Meeting_IsMeetingPrivate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        public static string Meeting_Leader_Name {
            get {
                return ResourceManager.GetString("Meeting_Leader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přednášející.
        /// </summary>
        public static string Meeting_Lecturer_Name {
            get {
                return ResourceManager.GetString("Meeting_Lecturer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hlavní leader.
        /// </summary>
        public static string Meeting_MainLeader_Name {
            get {
                return ResourceManager.GetString("Meeting_MainLeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cílová skupina.
        /// </summary>
        public static string Meeting_MeetingKind_Name {
            get {
                return ResourceManager.GetString("Meeting_MeetingKind_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Meeting_MeetingType_Name {
            get {
                return ResourceManager.GetString("Meeting_MeetingType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizátor.
        /// </summary>
        public static string Meeting_Organizer_Name {
            get {
                return ResourceManager.GetString("Meeting_Organizer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaplacená částka.
        /// </summary>
        public static string Meeting_PaidAmmount_Name {
            get {
                return ResourceManager.GetString("Meeting_PaidAmmount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Meeting_Price_Name {
            get {
                return ResourceManager.GetString("Meeting_Price_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední den rezervace.
        /// </summary>
        public static string Meeting_RegisterDeadline_Name {
            get {
                return ResourceManager.GetString("Meeting_RegisterDeadline_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bydliště.
        /// </summary>
        public static string Meeting_Residence_Name {
            get {
                return ResourceManager.GetString("Meeting_Residence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druhý leader.
        /// </summary>
        public static string Meeting_SecondaryLeader_Name {
            get {
                return ResourceManager.GetString("Meeting_SecondaryLeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druhý organizátor.
        /// </summary>
        public static string Meeting_SecondaryOrganizer_Name {
            get {
                return ResourceManager.GetString("Meeting_SecondaryOrganizer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlásit.
        /// </summary>
        public static string Meeting_Sign_Name {
            get {
                return ResourceManager.GetString("Meeting_Sign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifický symbol.
        /// </summary>
        public static string Meeting_SpecificSymbol_Name {
            get {
                return ResourceManager.GetString("Meeting_SpecificSymbol_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        public static string Meeting_StartTime_Name {
            get {
                return ResourceManager.GetString("Meeting_StartTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        public static string Meeting_Time_Name {
            get {
                return ResourceManager.GetString("Meeting_Time_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        public static string Meeting_Type_Name {
            get {
                return ResourceManager.GetString("Meeting_Type_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlásit.
        /// </summary>
        public static string Meeting_Unsign_Name {
            get {
                return ResourceManager.GetString("Meeting_Unsign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Webináře.
        /// </summary>
        public static string Meeting_WebinarUrl_Name {
            get {
                return ResourceManager.GetString("Meeting_WebinarUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka z bankovního účtu.
        /// </summary>
        public static string MeetingAttendee_BankAccountHistoryNote_Name {
            get {
                return ResourceManager.GetString("MeetingAttendee_BankAccountHistoryNote_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umí nakupovat.
        /// </summary>
        public static string PeopleContact_AbleToPurchase_Name {
            get {
                return ResourceManager.GetString("PeopleContact_AbleToPurchase_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Cashback.
        /// </summary>
        public static string PeopleContact_AutoCashback_Name {
            get {
                return ResourceManager.GetString("PeopleContact_AutoCashback_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno kontaktu.
        /// </summary>
        public static string PeopleContact_FullName_Name {
            get {
                return ResourceManager.GetString("PeopleContact_FullName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vysvětlení věrnostního systému.
        /// </summary>
        public static string PeopleContact_LoyaltySystemExplained_Name {
            get {
                return ResourceManager.GetString("PeopleContact_LoyaltySystemExplained_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaslání peněz na nákupní konto.
        /// </summary>
        public static string PeopleContact_MoneyToPurchaseAccountSended_Name {
            get {
                return ResourceManager.GetString("PeopleContact_MoneyToPurchaseAccountSended_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Má své jednotky.
        /// </summary>
        public static string PeopleContact_OwnUnitsContained_Name {
            get {
                return ResourceManager.GetString("PeopleContact_OwnUnitsContained_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 2. telefonátu.
        /// </summary>
        public static string PeopleContact_SecondContacted_Name {
            get {
                return ResourceManager.GetString("PeopleContact_SecondContacted_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 2. schůzky.
        /// </summary>
        public static string PeopleContact_SecondMeeting_Name {
            get {
                return ResourceManager.GetString("PeopleContact_SecondMeeting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. dosledovací email odeslán.
        /// </summary>
        public static string PeopleContact_SecondTrackingEmailSent_Name {
            get {
                return ResourceManager.GetString("PeopleContact_SecondTrackingEmailSent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení shopping plánu.
        /// </summary>
        public static string PeopleContact_ShoppingPlanBackSet_Name {
            get {
                return ResourceManager.GetString("PeopleContact_ShoppingPlanBackSet_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 3. schůzky.
        /// </summary>
        public static string PeopleContact_ThirdMeeting_Name {
            get {
                return ResourceManager.GetString("PeopleContact_ThirdMeeting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosledovací email odeslán.
        /// </summary>
        public static string PeopleContact_TrackingEmailSent_Name {
            get {
                return ResourceManager.GetString("PeopleContact_TrackingEmailSent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportovatelný prefix.
        /// </summary>
        public static string PhoneNumberPrefix_ExportablePrefix_Name {
            get {
                return ResourceManager.GetString("PhoneNumberPrefix_ExportablePrefix_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulární výraz pro porovnání s importovanými daty.
        /// </summary>
        public static string PhoneNumberPrefix_MatchRegex_Name {
            get {
                return ResourceManager.GetString("PhoneNumberPrefix_MatchRegex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulární výraz pro odstranění předvolby.
        /// </summary>
        public static string PhoneNumberPrefix_ReplaceRegex_Name {
            get {
                return ResourceManager.GetString("PhoneNumberPrefix_ReplaceRegex_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasdílet s.
        /// </summary>
        public static string SharedContact_ToUserId_Name {
            get {
                return ResourceManager.GetString("SharedContact_ToUserId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Členové týmu.
        /// </summary>
        public static string Team_MemberIds_Name {
            get {
                return ResourceManager.GetString("Team_MemberIds_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastník týmu.
        /// </summary>
        public static string Team_Owner_Name {
            get {
                return ResourceManager.GetString("Team_Owner_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuální KS.
        /// </summary>
        public static string TopTen_ActualCareerStage_Name {
            get {
                return ResourceManager.GetString("TopTen_ActualCareerStage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Další školení.
        /// </summary>
        public static string TopTen_AdditionalTraining_Name {
            get {
                return ResourceManager.GetString("TopTen_AdditionalTraining_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedení Porad.
        /// </summary>
        public static string TopTen_ConductingMeetings_Name {
            get {
                return ResourceManager.GetString("TopTen_ConductingMeetings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downline uživatel.
        /// </summary>
        public static string TopTen_DownlineUser_Name {
            get {
                return ResourceManager.GetString("TopTen_DownlineUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední kontakt.
        /// </summary>
        public static string TopTen_LastContact_Name {
            get {
                return ResourceManager.GetString("TopTen_LastContact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kariérní dlouhodobý cíl.
        /// </summary>
        public static string TopTen_LongTermCareerGoal_Name {
            get {
                return ResourceManager.GetString("TopTen_LongTermCareerGoal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD I.
        /// </summary>
        public static string TopTen_Od1_Name {
            get {
                return ResourceManager.GetString("TopTen_Od1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD II.
        /// </summary>
        public static string TopTen_Od2_Name {
            get {
                return ResourceManager.GetString("TopTen_Od2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rétorika.
        /// </summary>
        public static string TopTen_Rhetoric_Name {
            get {
                return ResourceManager.GetString("TopTen_Rhetoric_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkce.
        /// </summary>
        public static string TopTen_Role_Name {
            get {
                return ResourceManager.GetString("TopTen_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kariérní krátkodobý cíl.
        /// </summary>
        public static string TopTen_ShorTermCareerGoal_Name {
            get {
                return ResourceManager.GetString("TopTen_ShorTermCareerGoal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNS.
        /// </summary>
        public static string TopTen_Sns_Name {
            get {
                return ResourceManager.GetString("TopTen_Sns_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYP.
        /// </summary>
        public static string TopTen_Status_Name {
            get {
                return ResourceManager.GetString("TopTen_Status_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vedení Týmu.
        /// </summary>
        public static string TopTen_TeamLeadershipping_Name {
            get {
                return ResourceManager.GetString("TopTen_TeamLeadershipping_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tréning BI-Prezentace.
        /// </summary>
        public static string TopTen_TrainingBiPresentation_Name {
            get {
                return ResourceManager.GetString("TopTen_TrainingBiPresentation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tréning telefonát.
        /// </summary>
        public static string TopTen_TrainingPhone_Name {
            get {
                return ResourceManager.GetString("TopTen_TrainingPhone_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tréning ST-Přednášky.
        /// </summary>
        public static string TopTen_TrainingStLecture_Name {
            get {
                return ResourceManager.GetString("TopTen_TrainingStLecture_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tréning video.
        /// </summary>
        public static string TopTen_TrainingVideo_Name {
            get {
                return ResourceManager.GetString("TopTen_TrainingVideo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titul.
        /// </summary>
        public static string User_Title_Name {
            get {
                return ResourceManager.GetString("User_Title_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval automatického odhlášení.
        /// </summary>
        public static string UserProfile_AutomaticLogoutInterval_Name {
            get {
                return ResourceManager.GetString("UserProfile_AutomaticLogoutInterval_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA - Commercial Assistant.
        /// </summary>
        public static string UserProfile_Ca_Name {
            get {
                return ResourceManager.GetString("UserProfile_Ca_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto.
        /// </summary>
        public static string UserProfile_ClaAccessAmount_Name {
            get {
                return ResourceManager.GetString("UserProfile_ClaAccessAmount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum vypršení přístupu.
        /// </summary>
        public static string UserProfile_ClaAccessExpired_Name {
            get {
                return ResourceManager.GetString("UserProfile_ClaAccessExpired_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roční poplatek za přístup.
        /// </summary>
        public static string UserProfile_ClaAccessYearlyAccess_Name {
            get {
                return ResourceManager.GetString("UserProfile_ClaAccessYearlyAccess_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Calendar ID.
        /// </summary>
        public static string UserProfile_GoogleCalendarId_Name {
            get {
                return ResourceManager.GetString("UserProfile_GoogleCalendarId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Credentials JSON.
        /// </summary>
        public static string UserProfile_GoogleCredentialsJson_Name {
            get {
                return ResourceManager.GetString("UserProfile_GoogleCredentialsJson_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soukromé události.
        /// </summary>
        public static string UserProfile_IsEventsPrivate_Name {
            get {
                return ResourceManager.GetString("UserProfile_IsEventsPrivate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum posledního přístupu.
        /// </summary>
        public static string UserProfile_LastAccessed_Name {
            get {
                return ResourceManager.GetString("UserProfile_LastAccessed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk.
        /// </summary>
        public static string UserProfile_LCID_Name {
            get {
                return ResourceManager.GetString("UserProfile_LCID_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSP Coach.
        /// </summary>
        public static string UserProfile_MspCoach_Name {
            get {
                return ResourceManager.GetString("UserProfile_MspCoach_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktů.
        /// </summary>
        public static string UserProfile_PeopleContactCount_Name {
            get {
                return ResourceManager.GetString("UserProfile_PeopleContactCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezentující.
        /// </summary>
        public static string UserProfile_Presenting_Name {
            get {
                return ResourceManager.GetString("UserProfile_Presenting_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas upozornění.
        /// </summary>
        public static string UserProfile_ReminderTime_Name {
            get {
                return ResourceManager.GetString("UserProfile_ReminderTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS-mail.
        /// </summary>
        public static string UserProfile_SmsEmail_Name {
            get {
                return ResourceManager.GetString("UserProfile_SmsEmail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Používat Google kalendář.
        /// </summary>
        public static string UserProfile_UseGoogleCalendar_Name {
            get {
                return ResourceManager.GetString("UserProfile_UseGoogleCalendar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesílat emaily.
        /// </summary>
        public static string UserProfile_UserMail_Name {
            get {
                return ResourceManager.GetString("UserProfile_UserMail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno.
        /// </summary>
        public static string UserProfile_UserName_Name {
            get {
                return ResourceManager.GetString("UserProfile_UserName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesílat SMS.
        /// </summary>
        public static string UserProfile_UseSms_Name {
            get {
                return ResourceManager.GetString("UserProfile_UseSms_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to všichni uživatelé.
        /// </summary>
        public static string Video_AllUsers_Name {
            get {
                return ResourceManager.GetString("Video_AllUsers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka záznamu v sekundách.
        /// </summary>
        public static string Video_Duration_Name {
            get {
                return ResourceManager.GetString("Video_Duration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tělo emailu odesílatele.
        /// </summary>
        public static string Video_EmailSenderBody_Name {
            get {
                return ResourceManager.GetString("Video_EmailSenderBody_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor videa.
        /// </summary>
        public static string Video_File_Name {
            get {
                return ResourceManager.GetString("Video_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpřístupněné uživatelům.
        /// </summary>
        public static string Video_VideoUsers_Name {
            get {
                return ResourceManager.GetString("Video_VideoUsers_Name", resourceCulture);
            }
        }
    }
}
