//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GoogleCalendarResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleCalendarResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Resources.GoogleCalendarResource", typeof(GoogleCalendarResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt: {0} {1}:
        ///Vysvětlit věrnostní výhody, naučit &quot;Google&quot; systém, naplánovat první společné schůzky..
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterBusinessInfoParticipatedAsync_Description {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterBusinessInfoParticipatedAsync_Descriptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} - 3. schůzka.
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterBusinessInfoParticipatedAsync_Summary {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterBusinessInfoParticipatedAsync_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt: {0} {1}:
        ///Zjistit, zda kontaktu dorazil e-mail, zda se již stačil podívat na přílohy a domluvit si druhou schůzku..
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterPresentedAsync1_Description {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterPresentedAsync1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} - 2. telefonát.
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterPresentedAsync1_Summary {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterPresentedAsync1_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt: {0} {1}:
        ///Doprovodit kontakt na BI, dosledovat jej po BI, dotázat se, zda chce dále pracovat a tvořit síť a svůj příjem? (Ano/ne).
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterPresentedAsync2_Description {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterPresentedAsync2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} - Business Info.
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterPresentedAsync2_Summary {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterPresentedAsync2_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt: {0} {1}:
        ///Provést eventuálně registraci, pokud již neproběhla, naučit nakupovat, online, poslání peněz na účet na vyzkoušení mobilní platby, poukázky, informace o BI a ST..
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterSecondContactedAsync_Description {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterSecondContactedAsync_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} - 2. schůzka.
        /// </summary>
        public static string PeopleContactController_CreateEventsAfterSecondContactedAsync_Summary {
            get {
                return ResourceManager.GetString("PeopleContactController_CreateEventsAfterSecondContactedAsync_Summary", resourceCulture);
            }
        }
    }
}
