//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListItemsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListItemsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Resources.ListItemsResource", typeof(ListItemsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 min.
        /// </summary>
        public static string AutomaticLogoutIntervalType_SixtyMinutes {
            get {
                return ResourceManager.GetString("AutomaticLogoutIntervalType_SixtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 min.
        /// </summary>
        public static string AutomaticLogoutIntervalType_TenMinutes {
            get {
                return ResourceManager.GetString("AutomaticLogoutIntervalType_TenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 min.
        /// </summary>
        public static string AutomaticLogoutIntervalType_ThirtyMinutes {
            get {
                return ResourceManager.GetString("AutomaticLogoutIntervalType_ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 min.
        /// </summary>
        public static string AutomaticLogoutIntervalType_TwentyMinutes {
            get {
                return ResourceManager.GetString("AutomaticLogoutIntervalType_TwentyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte bankovní účet.
        /// </summary>
        public static string BankAccount_DropDownListTitle {
            get {
                return ResourceManager.GetString("BankAccount_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístup.
        /// </summary>
        public static string BankAccountType_ApplicationAccess {
            get {
                return ResourceManager.GetString("BankAccountType_ApplicationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přístup do aplikace.
        /// </summary>
        public static string BankAccountType_ApplicationAccess_LongName {
            get {
                return ResourceManager.GetString("BankAccountType_ApplicationAccess_LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI MSP Wrk Lead.
        /// </summary>
        public static string BankAccountType_BiOrMspEveningOrWorkshopsOrLeaders {
            get {
                return ResourceManager.GetString("BankAccountType_BiOrMspEveningOrWorkshopsOrLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI, MSP Evening, Workshopy nebo Leaders.
        /// </summary>
        public static string BankAccountType_BiOrMspEveningOrWorkshopsOrLeaders_LongName {
            get {
                return ResourceManager.GetString("BankAccountType_BiOrMspEveningOrWorkshopsOrLeaders_LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Kotásek.
        /// </summary>
        public static string BankAccountType_DavidKotasekTraining {
            get {
                return ResourceManager.GetString("BankAccountType_DavidKotasekTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Školení Davida Kotáska.
        /// </summary>
        public static string BankAccountType_DavidKotasekTraining_LongName {
            get {
                return ResourceManager.GetString("BankAccountType_DavidKotasekTraining_LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte typ bankovního účtu.
        /// </summary>
        public static string BankAccountType_DropDownListTitle {
            get {
                return ResourceManager.GetString("BankAccountType_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string BankAccountType_Others {
            get {
                return ResourceManager.GetString("BankAccountType_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string BankAccountType_Others_LongName {
            get {
                return ResourceManager.GetString("BankAccountType_Others_LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setkání týmu, Business Info.
        /// </summary>
        public static string BankAccountType_TeamMeeting {
            get {
                return ResourceManager.GetString("BankAccountType_TeamMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setkání Týmu.
        /// </summary>
        public static string BankAccountType_TeamMeeting_LongName {
            get {
                return ResourceManager.GetString("BankAccountType_TeamMeeting_LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Převodní kurz: {1:N2} {0}).
        /// </summary>
        public static string Currency_CZKItemTitle {
            get {
                return ResourceManager.GetString("Currency_CZKItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Převodní kurz: {1} {0}/{2}, Převod na: {3:N2} {0}).
        /// </summary>
        public static string Currency_OtherItemTitle {
            get {
                return ResourceManager.GetString("Currency_OtherItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte typ měny.
        /// </summary>
        public static string CurrencyType_DropDownListTitle {
            get {
                return ResourceManager.GetString("CurrencyType_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte okres.
        /// </summary>
        public static string District_DropDownListTitle {
            get {
                return ResourceManager.GetString("District_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte hlavního leadera.
        /// </summary>
        public static string MainLeader_DropDownListTitle {
            get {
                return ResourceManager.GetString("MainLeader_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte typ návodu.
        /// </summary>
        public static string ManualType_DropDownListTitle {
            get {
                return ResourceManager.GetString("ManualType_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozvané.
        /// </summary>
        public static string MeetingKind_Invited {
            get {
                return ResourceManager.GetString("MeetingKind_Invited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeLine.
        /// </summary>
        public static string MeetingKind_LifeLine {
            get {
                return ResourceManager.GetString("MeetingKind_LifeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSP.
        /// </summary>
        public static string MeetingKind_MSP {
            get {
                return ResourceManager.GetString("MeetingKind_MSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro všechny.
        /// </summary>
        public static string MeetingKind_Public {
            get {
                return ResourceManager.GetString("MeetingKind_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte název akce.
        /// </summary>
        public static string MeetingTitleType_DropDownListTitle {
            get {
                return ResourceManager.GetString("MeetingTitleType_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Info.
        /// </summary>
        public static string MeetingType_Bi {
            get {
                return ResourceManager.GetString("MeetingType_Bi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte typ akce.
        /// </summary>
        public static string MeetingType_DropDownListTitle {
            get {
                return ResourceManager.GetString("MeetingType_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaders.
        /// </summary>
        public static string MeetingType_Leaders {
            get {
                return ResourceManager.GetString("MeetingType_Leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSP Evening.
        /// </summary>
        public static string MeetingType_MspEvening {
            get {
                return ResourceManager.GetString("MeetingType_MspEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        public static string MeetingType_Ostatni {
            get {
                return ResourceManager.GetString("MeetingType_Ostatni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setkání týmu.
        /// </summary>
        public static string MeetingType_SetkaniTymu {
            get {
                return ResourceManager.GetString("MeetingType_SetkaniTymu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Školení Davida Kotáska.
        /// </summary>
        public static string MeetingType_SkoleniDavidaKotaska {
            get {
                return ResourceManager.GetString("MeetingType_SkoleniDavidaKotaska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webinář.
        /// </summary>
        public static string MeetingType_Webinar {
            get {
                return ResourceManager.GetString("MeetingType_Webinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshopy BI.
        /// </summary>
        public static string MeetingType_WorkshopyBi {
            get {
                return ResourceManager.GetString("MeetingType_WorkshopyBi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte.
        /// </summary>
        public static string PhoneNumberPrefix2Id_DropDownListTitle {
            get {
                return ResourceManager.GetString("PhoneNumberPrefix2Id_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string RoleAcronym_Admin {
            get {
                return ResourceManager.GetString("RoleAcronym_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL.
        /// </summary>
        public static string RoleAcronym_AdminLeader {
            get {
                return ResourceManager.GetString("RoleAcronym_AdminLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string RoleAcronym_AuthGuest {
            get {
                return ResourceManager.GetString("RoleAcronym_AuthGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string RoleAcronym_Leader {
            get {
                return ResourceManager.GetString("RoleAcronym_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrátor.
        /// </summary>
        public static string RoleType_Admin {
            get {
                return ResourceManager.GetString("RoleType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin - lídr.
        /// </summary>
        public static string RoleType_AdminLeader {
            get {
                return ResourceManager.GetString("RoleType_AdminLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autentizovaný host.
        /// </summary>
        public static string RoleType_AuthGuest {
            get {
                return ResourceManager.GetString("RoleType_AuthGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lídr.
        /// </summary>
        public static string RoleType_Leader {
            get {
                return ResourceManager.GetString("RoleType_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neznámý.
        /// </summary>
        public static string RoleType_Unknown {
            get {
                return ResourceManager.GetString("RoleType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte druhého leadera.
        /// </summary>
        public static string SecondaryLeader_DropDownListTitle {
            get {
                return ResourceManager.GetString("SecondaryLeader_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte druhého organizátora.
        /// </summary>
        public static string SecondaryOrganizer_DropDownListTitle {
            get {
                return ResourceManager.GetString("SecondaryOrganizer_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte typ.
        /// </summary>
        public static string Status_DropDownListTitle {
            get {
                return ResourceManager.GetString("Status_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozývající.
        /// </summary>
        public static string TopTenRole_Inviting {
            get {
                return ResourceManager.GetString("TopTenRole_Inviting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyoness lídr.
        /// </summary>
        public static string TopTenRole_LyonessLeader {
            get {
                return ResourceManager.GetString("TopTenRole_LyonessLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1.
        /// </summary>
        public static string TopTenRole_M1 {
            get {
                return ResourceManager.GetString("TopTenRole_M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M2.
        /// </summary>
        public static string TopTenRole_M2 {
            get {
                return ResourceManager.GetString("TopTenRole_M2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezentující.
        /// </summary>
        public static string TopTenRole_Presenting {
            get {
                return ResourceManager.GetString("TopTenRole_Presenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte uživatele.
        /// </summary>
        public static string UserProfile_DropDownListTitle {
            get {
                return ResourceManager.GetString("UserProfile_DropDownListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @moje.
        /// </summary>
        public static string UserProfile_MineItemTitle {
            get {
                return ResourceManager.GetString("UserProfile_MineItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte video.
        /// </summary>
        public static string Video_DropDownListTitle {
            get {
                return ResourceManager.GetString("Video_DropDownListTitle", resourceCulture);
            }
        }
    }
}
