//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Resources.MailResource", typeof(MailResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hesla.
        /// </summary>
        public static string AccountController_PasswordRecovery_Subject {
            get {
                return ResourceManager.GetString("AccountController_PasswordRecovery_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě Vám bylo změněno heslo do systému CLA. Pokud jste o změnu nežádali, prosím kontaktujte správce systému CLA. Pro přihlášení do systému CLA použijte prosím následující heslo:
        ///Heslo: {0}
        ///
        ///Prosím, přihlašte se do systému CLA a změňte si své heslo..
        /// </summary>
        public static string AccountController_PasswordRecovery_TextBody {
            get {
                return ResourceManager.GetString("AccountController_PasswordRecovery_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrace účtu.
        /// </summary>
        public static string AccountController_Register_Subject {
            get {
                return ResourceManager.GetString("AccountController_Register_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě Vám byl vytvořen účet v systému CLA. Pro přihlášení do systému CLA použijte prosím následující údaje:
        ///Přihlašovací jméno: {0}
        ///Heslo: {1}
        ///
        ///Prosím, přihlašte se do systému CLA a změňte si své heslo.
        ///
        ///Pro přihlášení do CLA použijte následující odkaz:
        ///{2}.
        /// </summary>
        public static string AccountController_Register_TextBody {
            get {
                return ResourceManager.GetString("AccountController_Register_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba v odesílání událostí do Google Calendar.
        /// </summary>
        public static string Calendar_InsertEvents_Subject {
            get {
                return ResourceManager.GetString("Calendar_InsertEvents_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to během odesílání událostí do Vašeho kalendáře došlo k chybě. Prosím zkontrolujte nastavení Google Calendar..
        /// </summary>
        public static string Calendar_InsertEvents_TextBody {
            get {
                return ResourceManager.GetString("Calendar_InsertEvents_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pěkný den,
        ///
        ///{0}
        ///
        ///S pozdravem,
        ///
        ///CLA System.
        ///
        ///---
        ///
        ///Tento email byl vygenerován automaticky. Neodpovídejte prosím na tento email..
        /// </summary>
        public static string Mail_AutomaticMailTextBodyTemplate {
            get {
                return ResourceManager.GetString("Mail_AutomaticMailTextBodyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme vysokou platbu pro přihlášení kontaktu {0} na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Celková odeslaná částka: {4} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_OrganizerContactPaymentIsHigh_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OrganizerContactPaymentIsHigh_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme nedostatečnou platbu kontaktu {0} pro přihlášení na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Prosím zkontrolujte platební údaje.
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Celková odeslaná částka: {4} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_OrganizerContactPaymentIsLow_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OrganizerContactPaymentIsLow_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme vysokou platbu pro přihlášení uživatele {0} na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Celková odeslaná částka: {4} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_OrganizerPaymentIsHigh_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OrganizerPaymentIsHigh_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme nedostatečnou platbu pro přihlášení uživatele {0} na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Celková odeslaná částka: {4} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_OrganizerPaymentIsLow_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OrganizerPaymentIsLow_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontakt {0} byl odhlášen z akce {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Na tuto akci již poslal(a) celkem {3} Kč..
        /// </summary>
        public static string MeetingController_OrganizerUnsignedContactWithPaidAmmount_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OrganizerUnsignedContactWithPaidAmmount_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uživatel {0} byl odhlášen z akce {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Na tuto akci již poslal(a) celkem {3} Kč..
        /// </summary>
        public static string MeetingController_OrganizerUnsignedWithPaidAmmount_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OrganizerUnsignedWithPaidAmmount_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme vysokou platbu Vašeho kontaktu {0} pro přihlášení na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Prosím zkontrolujte platební údaje.
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Celková odeslaná částka: {4} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_OwnerPaymentIsHigh_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OwnerPaymentIsHigh_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme nedostatečnou platbu Vašeho kontaktu {0} pro přihlášení na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Prosím zkontrolujte platební údaje.
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Celková odeslaná částka: {4} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_OwnerPaymentIsLow_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OwnerPaymentIsLow_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systém CLA přihlásil Váš kontakt {0} na akci {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Děkujeme a těšíme se na setkání..
        /// </summary>
        public static string MeetingController_OwnerRegisteredContact_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OwnerRegisteredContact_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systém CLA rezervoval místo Vašemu kontaktu {0} na akci {1} do {2}.
        ///Pokud do té doby neobdržíme platbu podle níže uvedených instrukcí, bude rezervace zrušena.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{3}
        ///
        ///Pokud je akce placená, prosím proveďte platbu podle následujících údajů:
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{4}
        ///
        ///Děkujeme a těšíme se na setkání..
        /// </summary>
        public static string MeetingController_OwnerSignedContact_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OwnerSignedContact_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš kontakt {0} byl odhlášen z akce {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}.
        /// </summary>
        public static string MeetingController_OwnerUnsignedContact_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OwnerUnsignedContact_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš kontakt {0} byl odhlášen z akce {1}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Na tuto akci již poslal(a) celkem {3} Kč. Pro finanční vyrovnání prosím kontaktujte organizátora akce..
        /// </summary>
        public static string MeetingController_OwnerUnsignedContactWithPaidAmmount_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_OwnerUnsignedContactWithPaidAmmount_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vysoká platba.
        /// </summary>
        public static string MeetingController_PaymentIsHigh_Subject {
            get {
                return ResourceManager.GetString("MeetingController_PaymentIsHigh_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme vysokou platbu pro přihlášení na akci {0}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{1}
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{2}
        ///
        ///Celková odeslaná částka: {3} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_PaymentIsHigh_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_PaymentIsHigh_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedostatečná platba.
        /// </summary>
        public static string MeetingController_PaymentIsLow_Subject {
            get {
                return ResourceManager.GetString("MeetingController_PaymentIsLow_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zaznamenali jsme nedostatečnou platbu pro přihlášení na akci {0}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{1}
        ///
        ///Prosím zkontrolujte platební údaje.
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{2}
        ///
        ///Celková odeslaná částka: {3} Kč.
        ///
        ///Děkujeme za pochopení..
        /// </summary>
        public static string MeetingController_PaymentIsLow_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_PaymentIsLow_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášení na akci.
        /// </summary>
        public static string MeetingController_Registered_Subject {
            get {
                return ResourceManager.GetString("MeetingController_Registered_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byl(a) jste úspěšně přihlášen(a) na akci {0}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{1}
        ///
        ///Děkujeme a těšíme se na setkání..
        /// </summary>
        public static string MeetingController_Registered_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_Registered_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervace na akci.
        /// </summary>
        public static string MeetingController_Signed_Subject {
            get {
                return ResourceManager.GetString("MeetingController_Signed_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systém CLA Vám rezervoval místo na akci {0} do {1}.
        ///Pokud do té doby neobdržíme platbu podle níže uvedených instrukcí, bude rezervace zrušena.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{2}
        ///
        ///Pokud je akce placená, prosím proveďte platbu podle následujících údajů:
        ///
        ///+ PLATEBNÍ ÚDAJE
        ///  ==============
        ///{3}
        ///
        ///Děkujeme a těšíme se na setkání..
        /// </summary>
        public static string MeetingController_Signed_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_Signed_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlášení z akce.
        /// </summary>
        public static string MeetingController_Unsigned_Subject {
            get {
                return ResourceManager.GetString("MeetingController_Unsigned_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byl(a) jste odhlášen(a) z akce {0}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{1}.
        /// </summary>
        public static string MeetingController_Unsigned_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_Unsigned_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byl(a) jste odhlášen(a) z akce {0}.
        ///
        ///+ DETAIL AKCE
        ///  ===========
        ///{1}
        ///
        ///Na tuto akci jste již poslal(a) celkem {2} Kč. Pro finanční vyrovnání prosím kontaktujte organizátora akce..
        /// </summary>
        public static string MeetingController_UnsignedWithPaidAmmount_TextBody {
            get {
                return ResourceManager.GetString("MeetingController_UnsignedWithPaidAmmount_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název: {0}
        ///Od: {1}
        ///Do: {2}
        ///Obec: {3}
        ///Ulice: {4}
        ///Organizátor: {5}
        ///Přednášející: {6}
        ///
        ///Potřebné s sebou:
        ///{7}
        ///
        ///Poznámka:
        ///{8}.
        /// </summary>
        public static string MeetingModelView_MeetingDetail_Text {
            get {
                return ResourceManager.GetString("MeetingModelView_MeetingDetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro tento typ akce nejsou žádné platební údaje..
        /// </summary>
        public static string MeetingModelView_NoPaymentInfo_Text {
            get {
                return ResourceManager.GetString("MeetingModelView_NoPaymentInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účet: {0}
        ///IBAN: {1}
        ///SWIFT: {2}
        ///Specifický symbol: {3}
        ///Variabilní symbol: {4}
        ///Cena: {5:N0} {6}.
        ///Poznámka pro příjemce: Vaše kontaktní telefonní číslo..
        /// </summary>
        public static string MeetingModelView_PaymentInfo_Text {
            get {
                return ResourceManager.GetString("MeetingModelView_PaymentInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLA nalezlo novou duplicitu kontaktů s Vaším kontaktem: {0} {1}. Váš kontakt ještě není registrován..
        /// </summary>
        public static string PeopleContactController_ProcessDuplicityAndGetStatusMessage_IsNotRegistrated_TextBody {
            get {
                return ResourceManager.GetString("PeopleContactController_ProcessDuplicityAndGetStatusMessage_IsNotRegistrated_Text" +
                        "Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLA nalezlo novou duplicitu kontaktů s Vaším kontaktem: {0} {1}. Váš kontakt je již registrován..
        /// </summary>
        public static string PeopleContactController_ProcessDuplicityAndGetStatusMessage_IsRegistrated_TextBody {
            get {
                return ResourceManager.GetString("PeopleContactController_ProcessDuplicityAndGetStatusMessage_IsRegistrated_TextBod" +
                        "y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicita kontaktu lidí.
        /// </summary>
        public static string PeopleContactController_ProcessDuplicityAndGetStatusMessage_Subject {
            get {
                return ResourceManager.GetString("PeopleContactController_ProcessDuplicityAndGetStatusMessage_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navýšení konta pro přístup.
        /// </summary>
        public static string TaskSchedulerController_AccessPaymentAccepted_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_AccessPaymentAccepted_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě jsme Vám navýšili konto pro přístup do aplikace o {0:N2} {1} na částku {2:N2} {1}..
        /// </summary>
        public static string TaskSchedulerController_AccessPaymentAccepted_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_AccessPaymentAccepted_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V současné době nejsou k dispozici žádné úkoly..
        /// </summary>
        public static string TaskSchedulerController_ExecuteCheckTasks_NoTasks {
            get {
                return ResourceManager.GetString("TaskSchedulerController_ExecuteCheckTasks_NoTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úkoly.
        /// </summary>
        public static string TaskSchedulerController_ExecuteCheckTasks_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_ExecuteCheckTasks_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v systému CLA máte následující úkoly.
        ///
        ///Aktuální úkoly:
        ///{0}
        ///Úkoly v prodlení:
        ///{1}
        ///Pro přihlášení do CLA použijte následující odkaz:
        ///{2}.
        /// </summary>
        public static string TaskSchedulerController_ExecuteCheckTasks_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_ExecuteCheckTasks_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedena konverze měn pro přístup do aplikace.
        /// </summary>
        public static string TaskSchedulerController_FoundConvertedAmountForAccess_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_FoundConvertedAmountForAccess_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to došlo k automatické konverzi měn.
        ///
        ///{0}.
        /// </summary>
        public static string TaskSchedulerController_FoundConvertedAmountForAccess_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_FoundConvertedAmountForAccess_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provedena konverze měn pro akci.
        /// </summary>
        public static string TaskSchedulerController_FoundConvertedAmountForMeeting_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_FoundConvertedAmountForMeeting_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to došlo k automatické konverzi měn.
        ///
        ///{0}.
        /// </summary>
        public static string TaskSchedulerController_FoundConvertedAmountForMeeting_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_FoundConvertedAmountForMeeting_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V příloze posíláme fakturu za přístup do aplikace CLA..
        /// </summary>
        public static string TaskSchedulerController_Invoice_Message {
            get {
                return ResourceManager.GetString("TaskSchedulerController_Invoice_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura za přístup do aplikace.
        /// </summary>
        public static string TaskSchedulerController_Invoice_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_Invoice_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omezení přístupu do aplikace.
        /// </summary>
        public static string TaskSchedulerController_NotificationAccessBlock_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_NotificationAccessBlock_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě Vám byl odebrán přístup do aplikace. Prosím prodlužte si Váš přístup podle následujících platebních informací.
        ///
        ///{0}.
        /// </summary>
        public static string TaskSchedulerController_NotificationAccessBlock_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_NotificationAccessBlock_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornění expirace přístupu do aplikace.
        /// </summary>
        public static string TaskSchedulerController_NotificationAccessExpiration_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_NotificationAccessExpiration_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dne {0:dd.MM.yyyy} Vám vyprší přístup do aplikace. Prosím prodlužte si Váš přístup podle následujících platebních informací.
        ///
        ///{1}.
        /// </summary>
        public static string TaskSchedulerController_NotificationAccessExpiration_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_NotificationAccessExpiration_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolení přístupu do aplikace.
        /// </summary>
        public static string TaskSchedulerController_NotificationAccessUnblock_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_NotificationAccessUnblock_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě Vám byl povolen přístup do aplikace..
        /// </summary>
        public static string TaskSchedulerController_NotificationAccessUnblock_TextBody {
            get {
                return ResourceManager.GetString("TaskSchedulerController_NotificationAccessUnblock_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video bylo přehráno.
        /// </summary>
        public static string TaskSchedulerController_SendLazyMails_Subject {
            get {
                return ResourceManager.GetString("TaskSchedulerController_SendLazyMails_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlášení kontaktu z akce.
        /// </summary>
        public static string UserProfileController_AttendeeWasRemoved_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_AttendeeWasRemoved_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě byl Váš kontakt {0} odebrán z akce {1}. Prosím kontaktujte organizátora akce.
        ///
        ///Detail akce: {2}.
        /// </summary>
        public static string UserProfileController_AttendeeWasRemoved_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_AttendeeWasRemoved_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokování účtu.
        /// </summary>
        public static string UserProfileController_Locked_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_Locked_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě Vám byl zablokován účet v systému CLA. Pro jeho odblokování prosím kontaktujte svého lídra nebo administrátora systému..
        /// </summary>
        public static string UserProfileController_Locked_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_Locked_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna hlavního leadera.
        /// </summary>
        public static string UserProfileController_MainLeaderChanged_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_MainLeaderChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě jste se stal hlavním leaderem akce {0}.
        ///
        ///Detail akce: {1}.
        /// </summary>
        public static string UserProfileController_MainLeaderChanged_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_MainLeaderChanged_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna organizátora.
        /// </summary>
        public static string UserProfileController_OrganizerChanged_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_OrganizerChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě jste se stal organizátorem akce {0}.
        ///
        ///Detail akce: {1}.
        /// </summary>
        public static string UserProfileController_OrganizerChanged_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_OrganizerChanged_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Změna druhého leadera.
        /// </summary>
        public static string UserProfileController_SecondaryLeaderChanged_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_SecondaryLeaderChanged_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě jste se stal druhým leaderem akce {0}.
        ///
        ///Detail akce: {1}.
        /// </summary>
        public static string UserProfileController_SecondaryLeaderChanged_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_SecondaryLeaderChanged_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odblokování účtu.
        /// </summary>
        public static string UserProfileController_Unlocked_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_Unlocked_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě Vám byl odblokován účet v systému CLA. Nyní se opět můžete přihlásit..
        /// </summary>
        public static string UserProfileController_Unlocked_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_Unlocked_TextBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odhlášení z akce.
        /// </summary>
        public static string UserProfileController_UserAttendeeWasRemoved_Subject {
            get {
                return ResourceManager.GetString("UserProfileController_UserAttendeeWasRemoved_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to právě jste byl odebrán z akce {0}. Prosím kontaktujte organizátora akce.
        ///
        ///Detail akce: {1}.
        /// </summary>
        public static string UserProfileController_UserAttendeeWasRemoved_TextBody {
            get {
                return ResourceManager.GetString("UserProfileController_UserAttendeeWasRemoved_TextBody", resourceCulture);
            }
        }
    }
}
