//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LBT.Resources.ValidationResource", typeof(ValidationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Váš přístup do aplikace vypršel. Prosím prodlužte si Váš přístup podle následujících platebních informací.&lt;br /&gt;
        ///&lt;pre&gt;{0}&lt;/pre&gt;.
        /// </summary>
        public static string Account_AccountAccessIsExpired_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_AccountAccessIsExpired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento účet je zablokován..
        /// </summary>
        public static string Account_AccountIsLocked_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_AccountIsLocked_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V současné době není možné měnit roli..
        /// </summary>
        public static string Account_CannotChangeRole_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_CannotChangeRole_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V současné době není možné provádět změnu na Vámi nově vybranou roli..
        /// </summary>
        public static string Account_CannotChangeRoleNow_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_CannotChangeRoleNow_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není možné měnit roli zpět na Autentizovaného hosta..
        /// </summary>
        public static string Account_CannotChangeRoleToAuthGuest_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_CannotChangeRoleToAuthGuest_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebylo možné odeslat email s heslem. Ověřte prosím emailovou adresu uživatele a opakujte proces později..
        /// </summary>
        public static string Account_CannotSendEmailForPasswordRecovery_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_CannotSendEmailForPasswordRecovery_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebylo možné odeslat email s heslem. Prosím proveďte obnovu hesla..
        /// </summary>
        public static string Account_CannotSendRegisterEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_CannotSendRegisterEmail_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Současné heslo je nesprávné nebo jste zadali špatně nové heslo..
        /// </summary>
        public static string Account_ChangePasswordUnsucceeded_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ChangePasswordUnsucceeded_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodsouhlasili jste obchodní podmínky, zpracování Vašich osobních údajů a zpracování osobních údajů již zadaných kontaktů. Opravdu chcete pokračovat?.
        /// </summary>
        public static string Account_CheckPolicies_NotCompletePrivacy_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_CheckPolicies_NotCompletePrivacy_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nové heslo a potvrzení nového hesla se musí shodovat..
        /// </summary>
        public static string Account_ConfirmPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota položky {0} musí být větší nebo rovno než aktuální datum..
        /// </summary>
        public static string Account_DateGreaterOrEqualThenNow_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_DateGreaterOrEqualThenNow_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel má zablokovaný účet..
        /// </summary>
        public static string Account_LockedAccount_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_LockedAccount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno nebo heslo je nesprávné. Zbývající počet pokusů: {0}..
        /// </summary>
        public static string Account_LoginFailed_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_LoginFailed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel se stejným Lyoness ID již existuje. Prosím zvolte jiné Lyoness ID..
        /// </summary>
        public static string Account_LyonessIdIsNotUnique_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_LyonessIdIsNotUnique_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při změně hesla došlo k chybě. Prosím kontaktujte administrátora..
        /// </summary>
        public static string Account_PasswordRecoveryFailed_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_PasswordRecoveryFailed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel se stejným mobilním telefonem již existuje. Prosím zvolte jiný mobilní telefon..
        /// </summary>
        public static string Account_Phone1IsNotUnique_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_Phone1IsNotUnique_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo musí obsahovat alespoň jedno písmeno malé abecedy, jedno písmeno velké abecedy a jedno číslo..
        /// </summary>
        public static string Account_RegexPasswordCharacters_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_RegexPasswordCharacters_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omlouváme se, Váš účet je dočasně zablokován na 30 minut kvůli pěti chybným zadání hesla..
        /// </summary>
        public static string Account_TooManyBadPasswords_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_TooManyBadPasswords_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatel neexistuje..
        /// </summary>
        public static string Account_UserDoesNotExist_ErrorMessage {
            get {
                return ResourceManager.GetString("Account_UserDoesNotExist_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není možné nalézt účet pro platbu za přístup. Kontaktujte prosím administrátora aplikace..
        /// </summary>
        public static string BankAccount_CannotFindBankAccount_ErrorMessage {
            get {
                return ResourceManager.GetString("BankAccount_CannotFindBankAccount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu smazat záznam. Bankovní účet se stále používá alespoň v jedné platné akci..
        /// </summary>
        public static string BankAccount_DeleteDBLinks_ErrorMessage {
            get {
                return ResourceManager.GetString("BankAccount_DeleteDBLinks_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Některý email nebylo možné odeslat. Pro více informací si přečtěte logy..
        /// </summary>
        public static string BulkMail_SomeEmailWasNotSent_ErrorMessage {
            get {
                return ResourceManager.GetString("BulkMail_SomeEmailWasNotSent_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu nalézt konverzní hodnotu pro převod {0} =&gt; {1}..
        /// </summary>
        public static string Currency_CannotProccessCurrencyChange_ErrorMessage {
            get {
                return ResourceManager.GetString("Currency_CannotProccessCurrencyChange_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špatný název souboru. Prosím přejmenujte soubor..
        /// </summary>
        public static string Global_BadFileName_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_BadFileName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze rozpoznat předvolbu telefonního čísla..
        /// </summary>
        public static string Global_BadPhoneNumberPrefix_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_BadPhoneNumberPrefix_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebylo možné se spojit s Google Calendar pro odeslání událostí do kalendáře..
        /// </summary>
        public static string Global_CannotConnectToGoogleCalendar_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_CannotConnectToGoogleCalendar_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Během komunikace s databází došlo k chybě. Kontaktujte prosím správce aplikace..
        /// </summary>
        public static string Global_DbCommunicationFailed_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_DbCommunicationFailed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu smazat záznam. Pravděpodobně se někde používá..
        /// </summary>
        public static string Global_DeleteRecord_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_DeleteRecord_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor není možné uložit. Zkuste to prosím znovu později..
        /// </summary>
        public static string Global_FileCannotBeSaved_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_FileCannotBeSaved_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor již existuje v úložišti. Vyberte prosím jiný soubor nebo soubor přejmenujte..
        /// </summary>
        public static string Global_FileExists_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_FileExists_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor je prázdný..
        /// </summary>
        public static string Global_FileIsEmpty_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_FileIsEmpty_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor je příliš velký. Maximální velikost je {0} MB..
        /// </summary>
        public static string Global_FileIsTooLarge_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_FileIsTooLarge_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte prosím správný formát video souboru..
        /// </summary>
        public static string Global_IncorrectFileFormat_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_IncorrectFileFormat_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyplňte alespoň jeden záznam..
        /// </summary>
        public static string Global_NoRecord_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_NoRecord_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota položky {0} již ve Vašem seznamu existuje..
        /// </summary>
        public static string Global_OwnUnique_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_OwnUnique_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonní číslo je příliš dlouhé..
        /// </summary>
        public static string Global_PhoneNumberIsTooLong_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_PhoneNumberIsTooLong_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonní číslo neobsahuje žádná čísla..
        /// </summary>
        public static string Global_PhoneNumberNotContainNumbers_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_PhoneNumberNotContainNumbers_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} musí být pouze celé kladné číslo..
        /// </summary>
        public static string Global_RangeIntPositive_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RangeIntPositive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} musí být pouze kladné číslo..
        /// </summary>
        public static string Global_RangeNumberPositive_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RangeNumberPositive_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} nemá platný formát e-mailu..
        /// </summary>
        public static string Global_RegexEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RegexEmail_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota položky {0} musí být ve tvaru xxx.xxx.xxx.xxx a nesmí nabývat hodnoty 000.000.000.000..
        /// </summary>
        public static string Global_RegexLyonessId_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RegexLyonessId_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota položky {0} musí být číslo.
        /// </summary>
        public static string Global_RegexNumber_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RegexNumber_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} musí být složena pouze z čísel bez mezer..
        /// </summary>
        public static string Global_RegexOnlyNumbers_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RegexOnlyNumbers_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} musí být v rozsahu od {1} do {2}..
        /// </summary>
        public static string Global_RegexOnlyNumbersRange_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RegexOnlyNumbersRange_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} nemá správný formát &apos;HH:mm&apos;..
        /// </summary>
        public static string Global_RegexTime_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RegexTime_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Položka {0} je povinná..
        /// </summary>
        public static string Global_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_Required_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; hodnota musí být vyplněna..
        /// </summary>
        public static string Global_RequiredValue_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_RequiredValue_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úložiště je plné. Zvolte prosím jiný soubor nebo odstraňte soubory z úložiště..
        /// </summary>
        public static string Global_StoreIsFull_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_StoreIsFull_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka položky {0} musí být maximálně {1} znaky..
        /// </summary>
        public static string Global_StringLength2_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_StringLength2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka položky {0} musí být maximálně {1} znaků..
        /// </summary>
        public static string Global_StringLength3_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_StringLength3_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Délka položky {0} musí být od {2} do {1} znaků..
        /// </summary>
        public static string Global_StringLengthMinMax2_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_StringLengthMinMax2_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; hodnota je příliš dlouhá..
        /// </summary>
        public static string Global_TooLongValue_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_TooLongValue_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala neočekávaná výjimka. Kontaktujte prosím administrátora..
        /// </summary>
        public static string Global_UnexpectedException_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_UnexpectedException_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota položky {0} musí být unikátní..
        /// </summary>
        public static string Global_Unique_ErrorMesage {
            get {
                return ResourceManager.GetString("Global_Unique_ErrorMesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota položky {0} není platná. Zkontrolujte prosím její hodnotu..
        /// </summary>
        public static string Global_Valid_ErrorMessage {
            get {
                return ResourceManager.GetString("Global_Valid_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není možné se spojit se službou Google API. Prosím ověřte hodnotu a znovu proveďte validaci..
        /// </summary>
        public static string GoogleAPI_CannotAuthentizedUser_ErrorMessage {
            get {
                return ResourceManager.GetString("GoogleAPI_CannotAuthentizedUser_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybraný druhý leader nesmí být v upline a downline seznamu hlavního leadera..
        /// </summary>
        public static string Meeting_BadSecondaryLeader_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_BadSecondaryLeader_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebylo možné uložit druhého organizátora k vybranému hlavnímu a druhému leaderovi. Prosím zvolte nového druhého organizátora..
        /// </summary>
        public static string Meeting_BadSecondaryOrganizer_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_BadSecondaryOrganizer_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účastník akce se stejným Lyoness ID je již přihlášen nebo rezervován..
        /// </summary>
        public static string Meeting_CannotAddDuplicateLyonessId_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CannotAddDuplicateLyonessId_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Již není možné měnit cenu nebo bankovní účet, pokud jsou u akce přiřazeni účastníci..
        /// </summary>
        public static string Meeting_CannotChangePrice_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CannotChangePrice_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu v databázi nalézt uživatele..
        /// </summary>
        public static string Meeting_CannotFindDbAttendee_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CannotFindDbAttendee_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu v databázi nalézt požadovanou akci..
        /// </summary>
        public static string Meeting_CannotFindMeeting_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CannotFindMeeting_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účastník je již přihlášen a není možné jej smazat..
        /// </summary>
        public static string Meeting_CannotRemoveSignedAttendee_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CannotRemoveSignedAttendee_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelze odhlásit uživatele z již proběhlé akce..
        /// </summary>
        public static string Meeting_CannotUnsignAttendeeFromPastMeeting_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CannotUnsignAttendeeFromPastMeeting_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacita akce nemůže být menší než počet již přihlášených účastníků..
        /// </summary>
        public static string Meeting_CapacityLowerThanRegistered_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CapacityLowerThanRegistered_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapacita akce byla překročena..
        /// </summary>
        public static string Meeting_CapacityOverloaded_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_CapacityOverloaded_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu smazat záznam. Nadpis akce se stále používá alespoň v jedné platné nebo archivované akci..
        /// </summary>
        public static string Meeting_DeleteDBLinks_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_DeleteDBLinks_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum a čas do musí být větší než aktuální čas..
        /// </summary>
        public static string Meeting_FinishedLowerThanNow_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_FinishedLowerThanNow_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte dostatečná oprávění k odhlášení účastníka akce..
        /// </summary>
        public static string Meeting_NotAllowedRemoveAttendee_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_NotAllowedRemoveAttendee_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokud chcete akci zpoplatnit, je potřeba vybrat bankovní účet, uvést cenu a poslední den rezervace..
        /// </summary>
        public static string Meeting_PriceBankAccountRegisterDeadline_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_PriceBankAccountRegisterDeadline_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslední den rezervace musí být menší než začátek akce..
        /// </summary>
        public static string Meeting_RegisterDeadlineGreaterThanStarted_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_RegisterDeadlineGreaterThanStarted_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím vyplňte správně druhý bankovní účet včetně ceny..
        /// </summary>
        public static string Meeting_SecondBankAccount_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_SecondBankAccount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Není možné vybrat druhý bankovní účet bez prvního účtu..
        /// </summary>
        public static string Meeting_SecondBankAccountWithoutFirstBankAccount_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_SecondBankAccountWithoutFirstBankAccount_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas do musí být větší nebo roven času od..
        /// </summary>
        public static string Meeting_StartedGreaterThanFinished_ErrorMessage {
            get {
                return ResourceManager.GetString("Meeting_StartedGreaterThanFinished_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno pro tuto e-mailovou adresu již existuje. Prosím vložte jinou e-mailovou adresu..
        /// </summary>
        public static string MembershipCreateStatus_DuplicateEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_DuplicateEmail_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno již existuje. Prosím vložte jiné přihlašovací jméno..
        /// </summary>
        public static string MembershipCreateStatus_DuplicateUserName_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_DuplicateUserName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpověď pro obnovu hesla je nesprávná. Prosím zkontrolujte hodnotu a zkuste to znovu..
        /// </summary>
        public static string MembershipCreateStatus_InvalidAnswer_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidAnswer_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailová adresa je neplatná. Prosím zkontrolujte adresu a zkuste to znovu..
        /// </summary>
        public static string MembershipCreateStatus_InvalidEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidEmail_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heslo je neplatné. Prosím vložte platné heslo..
        /// </summary>
        public static string MembershipCreateStatus_InvalidPassword_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidPassword_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka pro obnovu hesla je nesprávná. Prosím zkontrolujte hodnotu a zkuste to znovu..
        /// </summary>
        public static string MembershipCreateStatus_InvalidQuestion_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidQuestion_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlašovací jméno je neplatné. Prosím zkontrolujte hodnotu a zkuste to znovu..
        /// </summary>
        public static string MembershipCreateStatus_InvalidUserName_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_InvalidUserName_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala neznámá chyba. Prosím ověřte zadání a zkuste to znovu. Pokud bude problém přetrvávat, prosím kontaktujte systémového administrátora..
        /// </summary>
        public static string MembershipCreateStatus_Others_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_Others_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poskytovatel autentifikace odpověděl chybou. Prosím ověřte zadání a zkuste to znovu. Pokud bude problém přetrvávat, prosím kontaktujte systémového administrátora..
        /// </summary>
        public static string MembershipCreateStatus_ProviderError_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_ProviderError_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Požadavek na vytvoření uživatele byl zrušen. Prosím ověřte zadání a zkuste to znovu. Pokud bude problém přetrvávat, prosím kontaktujte systémového administrátora..
        /// </summary>
        public static string MembershipCreateStatus_UserRejected_ErrorMessage {
            get {
                return ResourceManager.GetString("MembershipCreateStatus_UserRejected_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Chyba v záznamu: {0}, {1}, {2}, {3}. {{0}}&quot;.
        /// </summary>
        public static string PeopleContact_BadImportedRow_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_BadImportedRow_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum Business info nesmí být větší než dnešní datum a menší než datum 1. schůzky..
        /// </summary>
        public static string PeopleContact_BusinessInfoParticipatedAndPresentedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_BusinessInfoParticipatedAndPresentedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu přečíst data CSV souboru na řádku {0}..
        /// </summary>
        public static string PeopleContact_CannorReadCsvRow_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_CannorReadCsvRow_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu přečíst hlavičku CSV souboru..
        /// </summary>
        public static string PeopleContact_CannotReadCsvHeader_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_CannotReadCsvHeader_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemohu přečíst položku video souboru. Kontaktujte prosím správce aplikace..
        /// </summary>
        public static string PeopleContact_CannotReadVideo_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_CannotReadVideo_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vybranému kontaktu nelze odeslat email..
        /// </summary>
        public static string PeopleContact_CannotSendEmail_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_CannotSendEmail_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musí být vyplněno alespoň jedno z polí mobilní telefon, skype nebo email 1..
        /// </summary>
        public static string PeopleContact_ChoosePhoneNumber1_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_ChoosePhoneNumber1_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení a jméno musí být vyplněno..
        /// </summary>
        public static string PeopleContact_LastNameAndFirstNameRequired_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_LastNameAndFirstNameRequired_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV data neobsahují sloupec &apos;{0}&apos;..
        /// </summary>
        public static string PeopleContact_MissingCsvHeader_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_MissingCsvHeader_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím potvrďte, že máte povolení ke zpracování osobních údajů od zadaného kontaktu/zadaných kontaktů..
        /// </summary>
        public static string PeopleContact_NotConfirmedPersonalData_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_NotConfirmedPersonalData_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosím potvrďte souhlas s obchodními podmínkami..
        /// </summary>
        public static string PeopleContact_NotConfirmedTermsAndConditions_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_NotConfirmedTermsAndConditions_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Během čtení CSV došlo k chybě: \n{0}.
        /// </summary>
        public static string PeopleContact_ParsingCsv_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_ParsingCsv_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musí být zvolena předvolba pro mobilní telefon..
        /// </summary>
        public static string PeopleContact_PhoneNumberPrefix1IsEmpty_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_PhoneNumberPrefix1IsEmpty_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 1. schůzky nesmí být větší než dnešní datum a menší než datum oslovení..
        /// </summary>
        public static string PeopleContact_PresentedAndFirstContactedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_PresentedAndFirstContactedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 2. telefonátu nesmí být větší než dnešní datum a menší než datum 1. schůzky..
        /// </summary>
        public static string PeopleContact_SecondContactedAndPresentedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_SecondContactedAndPresentedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 2. schůzky nesmí být větší než dnešní datum a menší než datum 2. telefonátu..
        /// </summary>
        public static string PeopleContact_SecondMeetingAndSecondContactedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_SecondMeetingAndSecondContactedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum odeslání 2. dosledovacího mailu nesmí být větší než dnešní den a menší než datum 2. telefonátu..
        /// </summary>
        public static string PeopleContact_SecondTrackingEmailSentAndSecondContactedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_SecondTrackingEmailSentAndSecondContactedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum 3. schůzky nesmí být větší než dnešní datum a menší než datum Business info..
        /// </summary>
        public static string PeopleContact_ThirdMeetingAndBusinessInfoParticipatedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_ThirdMeetingAndBusinessInfoParticipatedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum odeslání dosledovacího mailu nesmí být větší než dnešní den a menší než 1. schůzky..
        /// </summary>
        public static string PeopleContact_TrackingEmailSentAndPresentedComparing_ErrorMessage {
            get {
                return ResourceManager.GetString("PeopleContact_TrackingEmailSentAndPresentedComparing_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tohoto uživatele není možné povýšit..
        /// </summary>
        public static string UserProfile_CannotPromoteUser_ErrorMessage {
            get {
                return ResourceManager.GetString("UserProfile_CannotPromoteUser_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemůžete povýšit sám sebe..
        /// </summary>
        public static string UserProfile_CannotPromoteYourself_ErrorMessage {
            get {
                return ResourceManager.GetString("UserProfile_CannotPromoteYourself_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validace Google Credentials JSON a spojení s Google API selhalo. Zkuste validaci prosím později..
        /// </summary>
        public static string UserProfile_GoogleCredentialsJsonValidationFailed_ErrorMessage {
            get {
                return ResourceManager.GetString("UserProfile_GoogleCredentialsJsonValidationFailed_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum položky {0} nemá správný formát..
        /// </summary>
        public static string Validation_DateTime_ErrorMessage {
            get {
                return ResourceManager.GetString("Validation_DateTime_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsah položky {0} má špatný formát zástupných symbolů. Prosím ošetřete zástupné symboly..
        /// </summary>
        public static string Video_BadStringFormat_ErrorMessage {
            get {
                return ResourceManager.GetString("Video_BadStringFormat_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V současné době není možné video soubor smazat, pravděpodobně je přehráván. Zkuste to  prosím později..
        /// </summary>
        public static string Video_CannotRemoveFile_ErrorMessage {
            get {
                return ResourceManager.GetString("Video_CannotRemoveFile_ErrorMessage", resourceCulture);
            }
        }
    }
}
